FIX: Fix install failing and removal failing.
In other words, this actually makes shoppe usable. We *really* need a develop branch.

diff --git a/shoppe b/shoppe
--- a/shoppe
+++ b/shoppe
@@ -190,6 +190,7 @@ pkg_fetch() {
 			reposwithpkg="$reposwithpkg $repoID"
 		fi
 	done < "$repolist"
+	reposwithpkg=$(echo "$reposwithpkg" | sed -e 's/^[ \t]*//')
 	[[ -z "$reposwithpkg" ]] && echo -e "$p_error Could not find package $package. Check if your spelling is correct or add a repository that contains this package." && exit 1
 	bestline=$(grep "^$package " "$pkglist")
 	[[ -z "$bestline" ]] && bestline="$package 0 0"
@@ -208,13 +209,13 @@ pkg_fetch() {
 			bestrepo="$repo"
 		fi
 	done
+	[[ "$bestline" == "$originalline" ]] && echo -e "$p_info $package is already up to date." && current_uptodate="true" && return 0
 	repo="$bestrepo"
 	# shellcheck disable=SC2086
 	repotofetch="$(head -n1 $configdir/repodata/$repo)"
-	[[ "$bestline" == "$originalline" ]] && echo -e "$p_info $package is already up to date." && current_uptodate="true" && return 0
 	case $repotofetch in
-		"local: "*) cp "${repotofetch/local\:\ /}/$package/shoppepkg" "$tmpdir/$package/" && success="1" && [[ "$forcebuild" == "true" ]] && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg";;
-		"http: "*)  wget -q "${repotofetch/http\:\ /}/$package/shoppepkg" -O "$tmpdir/$package/shoppepkg" && success="1" && [[ "$forcebuild" == "true" ]] && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg";;
+		"local: "*) cp "${repotofetch/local\:\ /}/$package/shoppepkg" "$tmpdir/$package/" && success="1" && [[ "$forcebuild" == "true" ]] && [[ "$packagemake" != "true" ]] && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg";;
+		"http: "*)  wget -q "${repotofetch/http\:\ /}/$package/shoppepkg" -O "$tmpdir/$package/shoppepkg" && success="1" && [[ "$forcebuild" == "true" ]] && [[ "$packagemake" != "true" ]] && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg";;
 		*) echo -e "$p_debug Repo data file for id $repo does not contain repository path! Have you been tampering with the file? Run shoppe update to fix this.";;
 	esac
 	if [[ "$success" == "1" ]]; then return 0; else return 1; fi
@@ -249,7 +250,7 @@ pkg_cleanup() {
 	# Usage: pkg_cleanup
 	unset pkgname pkgdesc pkgarch pkgver revision license url depends optional makedepends conflicts archdependent source sourcetype tag
 	unset -f shoppepkg_preinstall shoppepkg_build shoppepkg_postinstall
-	unset nobuild
+	unset nobuild current_uptodate
 	[[ "$forcebuild" == "true" ]] && nobuild="false"
 }
 
@@ -266,12 +267,15 @@ pkg_install() {
 	type -t shoppepkg_preinstall &>/dev/null && echo -e "  - $p_info Running pre-install..." && shoppepkg_preinstall
 	if [[ "$nobuild" == "false" ]]; then
 		type -t shoppepkg_build &>/dev/null && echo -e "  - $p_info Building..." && ! shoppepkg_build && echo -e "$p_error Failed to build $package." && exit 1
+		cd "$tmpdir/$package"
 	else
 		contentchecksumvar="content_${arch}_checksum"
 		# shellcheck disable=SC2154
-		[[ "$nobuild" == "true" ]] && [[ "$(sha512sum content-$arch.tar.gz)" == "${!contentchecksumvar}" ]] && tar -xzf content-$arch.tar.gz
+		[[ "$nobuild" == "true" ]] && [[ "$(sha512sum content-$arch.tar.gz)" == "${!contentchecksumvar}" ]] && tar -xzf content-$arch.tar.gz -C content && echo -e "$p_info Successfully extracted package."
 	fi
-	! $suauth cp -rf content/* / && echo -e "$p_error Failed to install $package." && exit 1
+	! cd content && echo -e "$p_error Failed to install $package." && exit 1
+	! $suauth cp -rf . / && echo -e "$p_error Failed to install $package." && exit 1
+	cd "$tmpdir/$package"
 	[[ -e "$pkginfo/$package" ]] && rm -rf "${pkginfo:?}/${package:?}"
 	mkdir "$pkginfo/$package"
 	shopt -s globstar
@@ -337,7 +341,7 @@ frontend_init() {
 		command -v "$pm" &>/dev/null && break
 	done
 	case $pm in
-		pkg) # pkg (Termux)
+		pkg) # pkg (Termux, Debian-based with custom frontend)
 			frontend_install="$pm install"
 			frontend_remove="$pm remove"
 			frontend_update="$pm update"
@@ -446,9 +450,15 @@ shoppe_install() {
 			pkg_fetch
 			source "$tmpdir/$package/shoppepkg"
 			[[ "$package" = *"-git" ]] && echo -e "$p_info $package will be built manually." && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg" && nobuild=false
-			if [[ "$force" != "true" ]] && grep "^$package $pkgrel $pkgver" "$pkglist" &>/dev/null; then
-				grep "^$package " "$deplist" &>/dev/null && echo -e "$p_info Package $package was installed as a dependency. Setting as manually installed and skipping install..." && sed "/^$package\ /d" "$deplist" > "${deplist}-tmp" && mv "${deplist}-tmp" "$deplist"
-				echo -e "$p_info Package $package is already installed, skipping..."
+			#if [[ "$force" != "true" ]] && grep "^$package $pkgrel $pkgver" "$pkglist" &>/dev/null; then; fi
+			if [[ "$force" != "true" ]] && [[ "$current_uptodate" == "true" ]]; then
+				if grep "^$package " "$deplist" &>/dev/null; then
+					echo -e "$p_info Package $package was installed as a dependency. Setting as manually installed and skipping install..."
+					sed "/^$package\ /d" "$deplist" > "${deplist}-tmp"
+					mv "${deplist}-tmp" "$deplist"
+				else
+					echo -e "$p_info Package $package is already installed, skipping..."
+				fi
 				tocheck="${tocheck/$package/}"
 				continue
 			fi
@@ -521,7 +531,7 @@ shoppe_remove() {
 			grep "^$package " "$pkglist.frontend" && tofrontend="$tofrontend $package" && currentfrontend="true"
 			tocheck="${tocheck/$package/}"
 			# shellcheck disable=SC2086
-			[[ "$currentfrontend" != "true" ]] && tocheck="$tocheck $(cat $pkginfo/$package/dependencies)" && toremove="$package"
+			[[ "$currentfrontend" != "true" ]] && tocheck="$tocheck $(cat $pkginfo/$package/dependencies | tr '\n' ' ')" && toremove="$package"
 		done
 	done
 	[[ -z "$toremove" ]] && [[ -z "$tofrontend" ]] && echo -e "$p_error Nothing to remove!" && exit 1
