rename whim back to shoppe (fixes #4)

diff --git a/shoppe b/shoppe
--- a/shoppe
+++ b/shoppe
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 # shellcheck disable=SC1090,SC2001,SC1091,SC2219
 ##
-## whim! - a portable package manager that integrates with your current package manager
+## shoppe - a portable package manager that integrates with your current package manager
 version="1.0"
 ##
 ## Licensed under the MIT License
@@ -33,12 +33,12 @@ p_error="\033[31m!!\033[0m"
 p_debug="\033[35m~!\033[0m"
 
 ## Configuration. This is overwritten by the main config file ($configdir/config)
-configdir="$HOME/.config/whim"
+configdir="$HOME/.config/shoppe"
 repolist="$configdir/repositories"
 pkglist="$configdir/pkglist"
 deplist="$configdir/deplist"
 pkginfo="$configdir/pkginfo"
-tmpdir="/tmp/whim"
+tmpdir="/tmp/shoppe"
 
 force="false"
 
@@ -47,26 +47,26 @@ force="false"
 [[ ! -e "$configdir" ]] && mkdir -p "$configdir"
 [[ ! -e "$pkginfo" ]] && mkdir "$pkginfo"
 [[ ! -e "$configdir/repodata" ]] && mkdir "$configdir/repodata"
-[[ ! -e "$repolist" ]] && echo "http: https://raw.githubusercontent.com/whim-pm/whim-repo/master" > "$repolist"
+[[ ! -e "$repolist" ]] && echo "http: https://raw.githubusercontent.com/shoppepm/shoppe-repo/master" > "$repolist"
 [[ ! -e "$pkglist.frontend" ]] && touch "$pkglist.frontend"
 [[ ! -e "$pkglist" ]] && touch "$pkglist"
 
 ## Help (--help)
-whim_help() { echo "\
-Usage: whim function [options]
+shoppe_help() { echo "\
+Usage: shoppe function [options]
 
-whim is a portable package manager that uses the system's native
+shoppe is a portable package manager that uses the system's native
 package manager to suppliment packages that are not available in
-whim's repositories. It can act as a frontend for most package
+shoppe's repositories. It can act as a frontend for most package
 managers, and also works as a package manager itself.
 
 It can serve as an alternative to projects like snap or flatpak,
 as it allows packages to be installed on multiple distributions
 without having to create separate packages for each distribution.
-Unlike these projects, however, whim is not sandboxed,
+Unlike these projects, however, shoppe is not sandboxed,
 and everything is installed natively.
 
-More documentation is available at /usr/share/doc/whim.
+More documentation is available at /usr/share/doc/shoppe.
 
 Commands:
 
@@ -150,7 +150,7 @@ yesno() {
 # shellcheck disable=SC2154
 get_source() {
 	# This is a function used to get the source from the source variable.
-	# See docs/whimpkg.md
+	# See docs/shoppepkg.md
     if [[ "$sourcetype" == "compressed" ]]; then
         case $source in
             *.tar.gz) sourcetype="targz";;
@@ -213,9 +213,9 @@ pkg_fetch() {
 	repotofetch="$(head -n1 $configdir/repodata/$repo)"
 	[[ "$bestline" == "$originalline" ]] && echo -e "$p_info $package is already up to date." && current_uptodate="true" && return 0
 	case $repotofetch in
-		"local: "*) cp "${repotofetch/local\:\ /}/$package/whimpkg" "$tmpdir/$package/" && success="1" && [[ "$forcebuild" == "true" ]] && echo "nobuild='false'" >> "$tmpdir/$package/whimpkg";;
-		"http: "*)  wget -q "${repotofetch/http\:\ /}/$package/whimpkg" -O "$tmpdir/$package/whimpkg" && success="1" && [[ "$forcebuild" == "true" ]] && echo "nobuild='false'" >> "$tmpdir/$package/whimpkg";;
-		*) echo -e "$p_debug Repo data file for id $repo does not contain repository path! Have you been tampering with the file? Run whim update to fix this.";;
+		"local: "*) cp "${repotofetch/local\:\ /}/$package/shoppepkg" "$tmpdir/$package/" && success="1" && [[ "$forcebuild" == "true" ]] && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg";;
+		"http: "*)  wget -q "${repotofetch/http\:\ /}/$package/shoppepkg" -O "$tmpdir/$package/shoppepkg" && success="1" && [[ "$forcebuild" == "true" ]] && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg";;
+		*) echo -e "$p_debug Repo data file for id $repo does not contain repository path! Have you been tampering with the file? Run shoppe update to fix this.";;
 	esac
 	if [[ "$success" == "1" ]]; then return 0; else return 1; fi
 }
@@ -235,8 +235,8 @@ pkg_fetch_content() {
 	success="0"
 	case $repotofetch in
 		"local: "*) [[ -e "${repotofetch/local\:\ /}/$package/content.tar.gz" ]] && cp "${repotofetch/local\:\ /}/$package/content.tar.gz" "$tmpdir/$package/";;
-		"http: "*)  ! wget -q "${repotofetch/http\:\ /}/$package/content.tar.gz" -O "$tmpdir/$package/content.tar.gz" && echo -e "$p_warn Prebuilt files not found, defaulting to build mode..." && echo "nobuild='false'" >> "$tmpdir/$package/whimpkg";;
-		*) echo -e "$p_debug Repo data file for id $repo does not contain repository path! Have you been tampering with the file? Run whim update to fix this.";;
+		"http: "*)  ! wget -q "${repotofetch/http\:\ /}/$package/content.tar.gz" -O "$tmpdir/$package/content.tar.gz" && echo -e "$p_warn Prebuilt files not found, defaulting to build mode..." && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg";;
+		*) echo -e "$p_debug Repo data file for id $repo does not contain repository path! Have you been tampering with the file? Run shoppe update to fix this.";;
 	esac
 	if [[ "$success" == "1" ]]; then return 0; else return 1; fi
 }
@@ -244,11 +244,11 @@ pkg_fetch_content() {
 # Package helper functions
 
 pkg_cleanup() {
-	# This function cleans up after a whim package.
-	# Use this when you're running a loop that sources multiple whimpkgs.
+	# This function cleans up after a shoppe package.
+	# Use this when you're running a loop that sources multiple shoppepkgs.
 	# Usage: pkg_cleanup
 	unset pkgname pkgdesc pkgarch pkgver revision license website depends optional makedepends conflicts archdependent source sourcetype tag
-	unset -f whimpkg_preinstall whimpkg_build whimpkg_postinstall
+	unset -f shoppepkg_preinstall shoppepkg_build shoppepkg_postinstall
 	unset nobuild
 	[[ "$forcebuild" == "true" ]] && nobuild="false"
 }
@@ -259,13 +259,13 @@ pkg_install() {
 	pkg_cleanup
 	nobuild="true"
 	! cd "$tmpdir/$package" && echo -e "$p_error Could not get into temporary directory for $package. Make sure that you didn't wipe your temporary directory during the install process and that you can write to the temporary directory (currently $tmpdir)." && exit 1
-	source whimpkg
+	source shoppepkg
 	[[ "$forcebuild" == "true" ]] && nobuild="false"
 	# shellcheck disable=SC2154
 	[[ "$package" != "$pkgname" ]] && echo -e "$p_debug Package name and pkgname do not match (expected $package, got $pkgname). Please contact the package's maintainer."
-	type -t whimpkg_preinstall &>/dev/null && echo -e "  - $p_info Running pre-install..." && whimpkg_preinstall
+	type -t shoppepkg_preinstall &>/dev/null && echo -e "  - $p_info Running pre-install..." && shoppepkg_preinstall
 	if [[ "$nobuild" == "false" ]]; then
-		type -t whimpkg_build &>/dev/null && echo -e "  - $p_info Building..." && ! whimpkg_build && echo -e "$p_error Failed to build $package." && exit 1
+		type -t shoppepkg_build &>/dev/null && echo -e "  - $p_info Building..." && ! shoppepkg_build && echo -e "$p_error Failed to build $package." && exit 1
 	else
 		# shellcheck disable=SC2154
 		[[ "$nobuild" == "true" ]] && [[ "$(sha512sum content.tar.gz)" == "$sha512sum" ]] && tar -xzf content.tar.gz
@@ -281,7 +281,7 @@ pkg_install() {
 		[[ -f "$file" ]] && echo "${file/$PWD\/content/}" >> "$pkginfo/$package/content"
 	done
 	shopt -u globstar
-	type -t whimpkg_postinstall &>/dev/null && echo -e "  - $p_info Running post-install..." && ! whimpkg_postinstall && echo -e "$p_warn Post-install script failed, but package's files were already copied! It is reccomended to reinstall the package, and if that doesn't help, contact the package's maintainer."
+	type -t shoppepkg_postinstall &>/dev/null && echo -e "  - $p_info Running post-install..." && ! shoppepkg_postinstall && echo -e "$p_warn Post-install script failed, but package's files were already copied! It is reccomended to reinstall the package, and if that doesn't help, contact the package's maintainer."
 	if grep "^$package " "$pkglist"; then
 		sed "/^$package\ /d" "$pkglist" > "${pkglist}-tmp"
 		mv "${pkglist}-tmp" "$pkglist"
@@ -423,13 +423,13 @@ frontend_harvest() {
 ## Main functions
 
 # Install packages.
-whim_install() {
+shoppe_install() {
 	# Usage: installs packages specified in the $packages variable.
-	echo -e "$p_info Searching on whim repositories..."
+	echo -e "$p_info Searching on shoppe repositories..."
 	rm -rf "$tmpdir"
 	mkdir "$tmpdir"
 	[[ -z "$packages" ]] && echo -e "$p_error Nothing to install!" && exit 1
-	[[ ! -e "$configdir/repodata/1" ]] && echo -e "$p_warn No repositories fetched. Running update..." && whim_update
+	[[ ! -e "$configdir/repodata/1" ]] && echo -e "$p_warn No repositories fetched. Running update..." && shoppe_update
 #	totalrepos="$(find $configdir/repodata -mindepth 1 -type f | wc -l)" # total amount of repositories
 	tocheck="$packages"
 	# Until there's nothing to scan, get each package to scan and:
@@ -443,8 +443,8 @@ whim_install() {
 			success="0"
 			[[ "$pm" ]] && $frontend_query ^$package$ &>/dev/null && tofrontend="$tofrontend $package" && tocheck="${tocheck/$package/}" && continue
 			pkg_fetch
-			source "$tmpdir/$package/whimpkg"
-			[[ "$package" = *"-git" ]] && echo -e "$p_info $package will be built manually." && echo "nobuild='false'" >> "$tmpdir/$package/whimpkg" && nobuild=false
+			source "$tmpdir/$package/shoppepkg"
+			[[ "$package" = *"-git" ]] && echo -e "$p_info $package will be built manually." && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg" && nobuild=false
 			if [[ "$force" != "true" ]] && grep "^$package $pkgrel $pkgver" "$pkglist" &>/dev/null; then
 				grep "^$package " "$deplist" &>/dev/null && echo -e "$p_info Package $package was installed as a dependency. Setting as manually installed and skipping install..." && sed "/^$package\ /d" "$deplist" > "${deplist}-tmp" && mv "${deplist}-tmp" "$deplist"
 				echo -e "$p_info Package $package is already installed, skipping..."
@@ -473,16 +473,16 @@ whim_install() {
 	[[ "$tofrontend" ]] && echo -e "$p_info Installing packages from frontend..." && if $frontend_install $tofrontend; then echo -e "$p_info Updating installed package list..." && frontend_harvest; else echo -e "$p_error Failed to install." && exit 1; fi
 	for package in $toinstall; do
 		echo -e "$p_info Fetching prebuilt files..."
-		[[ "$packagemake" != "true" ]] && ! pkg_fetch_content && echo -e "$p_warn No prebuilt files found. This is most likely an issue with the package. If you're a package maintainer, use the +pm switch while building, and extract the resulting content.tar.gz from the package. If you don't want the package to have prebuilt files, add 'nobuild=false' to the whimpkg, or in case of building from a git repository rather than a static release, add -git to the end of your package name. whim will now attempt to install the package, however makedepends were not installed, so this is likely going to fail." && nobuild="false" && echo "nobuild='false'" >> "$tmpdir/$package/whimpkg"
+		[[ "$packagemake" != "true" ]] && ! pkg_fetch_content && echo -e "$p_warn No prebuilt files found. This is most likely an issue with the package. If you're a package maintainer, use the +pm switch while building, and extract the resulting content.tar.gz from the package. If you don't want the package to have prebuilt files, add 'nobuild=false' to the shoppepkg, or in case of building from a git repository rather than a static release, add -git to the end of your package name. shoppe will now attempt to install the package, however makedepends were not installed, so this is likely going to fail." && nobuild="false" && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg"
 		echo -e "$p_info Installing $package..."
 		let currentpkg++
 		pkg_install
 		if [[ "$packagemake" == "true" ]]; then
 			tar -czf content.tar.gz content
-			echo "sha512sum=$(sha512sum content.tar.gz)" >> "$tmpdir/$package/whimpkg"
+			echo "sha512sum=$(sha512sum content.tar.gz)" >> "$tmpdir/$package/shoppepkg"
 			mkdir "$tmpdir/$package/topackage"
 			mv content.tar.gz "$tmpdir/$package/topackage"
-			mv "$tmpdir/$package/whimpkg" "$tmpdir/$package/topackage"
+			mv "$tmpdir/$package/shoppepkg" "$tmpdir/$package/topackage"
 			tar -czf "$HOME/$package.tar.gz" -C "$tmpdir/$package/topackage" .
 			echo -e "$p_debug Package created. Path: $HOME/$package.tar.gz"
 		fi
@@ -490,7 +490,7 @@ whim_install() {
 }
 
 # Remove packages.
-whim_remove() {
+shoppe_remove() {
 	[[ -z "$packages" ]] && echo -e "$p_error Nothing to remove!" && exit 1
 	tocheck="$packages"
 	until [[ -z "${tocheck// }" ]]; do
@@ -538,7 +538,7 @@ whim_remove() {
 }
 
 # Update repository info.
-whim_update() {
+shoppe_update() {
 	[[ "$pm" ]] && echo -e "$p_info Fetching installed package list from frontend..." && frontend_harvest
 	[[ "$pm" ]] && $frontend_update
 	rm -rf "$configdir/repodata"
@@ -562,8 +562,8 @@ whim_update() {
 }
 
 # Upgrade packages
-whim_upgrade() {
-	whim_update
+shoppe_upgrade() {
+	shoppe_update
 	rm -rf "$tmpdir"
 	mkdir "$tmpdir"
 	while IFS="" read -r line || [[ -n "$line" ]]; do
@@ -590,12 +590,12 @@ whim_upgrade() {
 }
 
 # shellcheck disable=SC2154,SC2086
-whim_info() {
+shoppe_info() {
 	[[ -z "$packages" ]] && echo -e "$p_error No packages to display!"
 	for package in $packages; do
 		forcebuild="true"
 		! pkg_fetch && echo -e "$p_error Package $package does not exist!" && exit 1
-		source "$tmpdir/$package/whimpkg"
+		source "$tmpdir/$package/shoppepkg"
 		echo -e "$p_info Information about $package:"
 		grep "^$package " "$pkglist" &>"$tmpdir/pkgline" && echo -e "[Installed] ($(cat $tmpdir/pkgline))"
 		echo -e "Version: $pkgver (package revision $pkgrel)"
@@ -607,60 +607,60 @@ whim_info() {
 	return 0
 }
 
-whim_listall() {
+shoppe_listall() {
 	cat "$pkglist"
 	return 0
 }
 
-whim_fetch() {
+shoppe_fetch() {
 	# Fetches package files for packages
-	# Usage: packages="<packages>" whim_fetch
-	# Using this in whim code is not recommended. Please use fetch <package> instead.
+	# Usage: packages="<packages>" shoppe_fetch
+	# Using this in shoppe code is not recommended. Please use fetch <package> instead.
 	for package in $packages; do pkg_fetch "$package"; done
 }
 
 ## Option parsing
-[[ -z $1 ]] && echo -e "$p_error Nothing to do! Use 'whim help' for information about available commands." && exit 1
+[[ -z $1 ]] && echo -e "$p_error Nothing to do! Use 'shoppe help' for information about available commands." && exit 1
 case $1 in
-		'install') command="whim_install";;
-		'remove') command="whim_remove";;
-		'update') command="whim_update";;
-		'upgrade') command="whim_upgrade";;
-		'fetch') command="whim_fetch";;
-		'info') command="whim_info";;
-		'listall') command="whim_listall";;
-		'help'|'--help'|'-h'|'+help'|'+h') whim_help;;
-		'--version'|'-v'|'version') echo "whim $version"; exit 0;;
-		*) echo -e "$p_error Invalid command: $1. Use 'whim help' for information about available commands."; exit 1;;
+		'install') command="shoppe_install";;
+		'remove') command="shoppe_remove";;
+		'update') command="shoppe_update";;
+		'upgrade') command="shoppe_upgrade";;
+		'fetch') command="shoppe_fetch";;
+		'info') command="shoppe_info";;
+		'listall') command="shoppe_listall";;
+		'help'|'--help'|'-h'|'+help'|'+h') shoppe_help;;
+		'--version'|'-v'|'version') echo "shoppe $version"; exit 0;;
+		*) echo -e "$p_error Invalid command: $1. Use 'shoppe help' for information about available commands."; exit 1;;
 esac
 nocmd="${*/$1/}"
 for parse in $nocmd; do
 	case $parse in
 		-*) switches="$switches $parse";;
-		+*) whimswitches="$whimswitches $parse";;
+		+*) shoppeswitches="$shoppeswitches $parse";;
 		*) packages="$packages $parse";;
 	esac
 done
 command=$(echo "$command" | sed -e 's/^[ \t]*//')
 packages=$(echo "$packages" | sed -e 's/^[ \t]*//')
 switches=$(echo "$switches" | sed -e 's/^[ \t]*//')
-for switch in $whimswitches; do
+for switch in $shoppeswitches; do
 	case $switch in
 		"+skipfrontend"|"+sf") skipfrontend="true";;
 		"+noconfirm"|"+nc") noconfirm="true";;
 		"+forcebuild"|"+fb") nobuild="false"; forcebuild="true";;
 		"+packagemake"|"+pm") packagemake="true"; nobuild="false"; forcebuild="true";;
 		"+f"|"+force") force="true";;
-		'+h'|'+help') whim_help;;
-		'+version'|'+v') echo "whim $version"; exit 0;;
+		'+h'|'+help') shoppe_help;;
+		'+version'|'+v') echo "shoppe $version"; exit 0;;
 	esac
 done
 for switch in $switches; do
 	case $switch in
 		--noconfirm|-y) noconfirm="true";;
-		--help|-h) whim_help;;
+		--help|-h) shoppe_help;;
 		--force) force="true";;
-		'--version'|'-v') echo "whim $version"; exit 0;;
+		'--version'|'-v') echo "shoppe $version"; exit 0;;
 	esac
 done
 [[ "$skipfrontend" != "true" ]] && frontend_init
