move things around a bit

diff --git a/shoppe b/shoppe
--- a/shoppe
+++ b/shoppe
@@ -27,13 +27,13 @@ errorPrefix="$(color 1)!!$(color r)"
 debugPrefix="$(color 5)~~$(color r)"
 
 debugprint() {
-	[ "$debug" = "true" ] && echo -e "$debugPrefix $*"
+	[[ "$debug" == "true" ]] && echo -e "$debugPrefix $*"
 }
 
 echo -e "$debugPrefix shoppe version $version, architecture: $arch"
 
 # Don't run shoppe as root!
-if [ "$EUID" -eq 0 ]; then echo -e "$errorPrefix Don't run shoppe as root!"; exit 4; fi
+if [[ "$EUID" -eq 0 ]]; then echo -e "$errorPrefix Don't run shoppe as root!"; exit 4; fi
 
 configdir="$HOME/.config/shoppe"
 repofile="$configdir/repos"
@@ -43,9 +43,9 @@ packinfodir="$configdir/packinfo"
 tmpdir="$configdir/tmp"
 
 # Create shoppe files
-! [ -e "$configdir" ] && mkdir -p "$configdir"
-! [ -e "$repofile" ] && echo "GithubRepo=knuxify/shoppe-repos" > "$repofile"
-! [ -e "$packinfodir" ] && mkdir "$packinfodir"
+! [[ -e "$configdir" ]] && mkdir -p "$configdir"
+! [[ -e "$repofile" ]] && echo "GithubRepo=knuxify/shoppe-repos" > "$repofile"
+! [[ -e "$packinfodir" ]] && mkdir "$packinfodir"
 
 # TODO package managers
 unsupportedManagers="emerge nix-env"
@@ -71,13 +71,13 @@ done
 success() {
 	echo "$infoPrefix Success!"
 	# shellcheck disable=SC2154
-	if [ -z "$name" ]; then exit 0; else let success++; currentsuccess="1"; fi
+	if [[ -z "$name" ]]; then exit 0; else let success++; currentsuccess="1"; fi
 }
 
 yesno() {
-	if ! [ "$noconfirm" = "true" ]; then
+	if ! [[ "$noconfirm" == "true" ]]; then
 		choice=null
-		until [ "$choice" = "y" ] || [ "$choice" = "Y" ] || [ "$choice" = "n" ] || [ "$choice" = "N" ]; do
+		until [[ "$choice" == "y" ]] || [[ "$choice" == "Y" ]] || [[ "$choice" == "n" ]] || [[ "$choice" == "N" ]]; do
 			read -p "$yesnotxt" -ren1 choice
 			if [ -z "$choice" ]; then choice="$1"; fi
 		done
@@ -85,7 +85,7 @@ yesno() {
 		echo "$yesnotxt$1"
 		choice="$1"
 	fi
-	if [ "$choice" = "Y" ] || [ "$choice" = "y" ]; then choice="yes"; else choice="no"; fi
+	if [[ "$choice" == "Y" ]] || [[ "$choice" == "y" ]]; then choice="yes"; else choice="no"; fi
 }
 
 getpkg() {
@@ -105,8 +105,8 @@ fetch() {
 	for todownload in shoppepkg 'content.tar.gz'; do
 		while IFS="" read -r repo; do
 			case $repo in
-				GithubRepo=*) wget -q https://raw.githubusercontent.com/"${repo/GithubRepo=/}"/master/"$arch"/"$dpackage"/"$todownload" -O "$tmpdir"/"$todownload" && success="true"; ! [ "$?" = "0" ] && wget -q https://raw.githubusercontent.com/"${repo/GithubRepo=/}"/master/all/"$dpackage"/"$todownload" -O "$tmpdir"/"$todownload" && success="true";;
-				Local=*) cp -f "${repo/Local=/}/$arch/$dpackage/$todownload" "$tmpdir"/ &>/dev/null && success="true"; ! [ "$?" = "0" ] && cp -f "${repo/Local=/}/all/$dpackage/$todownload" "$tmpdir"/ &>/dev/null && success="true";;
+				GithubRepo=*) wget -q https://raw.githubusercontent.com/"${repo/GithubRepo=/}"/master/"$arch"/"$dpackage"/"$todownload" -O "$tmpdir"/"$todownload" && success="true"; ! [[ "$?" == "0" ]] && wget -q https://raw.githubusercontent.com/"${repo/GithubRepo=/}"/master/all/"$dpackage"/"$todownload" -O "$tmpdir"/"$todownload" && success="true";;
+				Local=*) cp -f "${repo/Local=/}/$arch/$dpackage/$todownload" "$tmpdir"/ &>/dev/null && success="true"; ! [[ "$?" == "0" ]] && cp -f "${repo/Local=/}/all/$dpackage/$todownload" "$tmpdir"/ &>/dev/null && success="true";;
 			esac
 		done < $repofile
 	done
@@ -115,21 +115,21 @@ fetch() {
 # Functions
 pinstall() {
 	depsuccess="false"
-	if [ -z "$packages" ]; then echo -e "$errorPrefix Nothing to install!"; exit 2; fi
-	if ! [ "$skipfrontend" = "true" ]; then
+	if [[ -z "$packages" ]]; then echo -e "$errorPrefix Nothing to install!"; exit 2; fi
+	if ! [[ "$skipfrontend" == "true" ]]; then
 		for pm in $installed; do
 			echo -e "$infoPrefix Using $pm..."
 			case $pm in
-				apt|apt-get|yum|dnf|eopkg|zypper) sudo "$pm" install $packages $switches && if [ -z "$depinstall" ]; then success; else depsuccess="true"; break; fi;;
-				pkg) "$pm" install $packages $switches && if [ -z "$depinstall" ]; then success; else depsuccess="true"; break; fi;;
-				pacman) sudo "$pm" -S $packages $switches --needed && if [ -z "$depinstall" ]; then success; else depsuccess="true"; break; fi;;
-				yaourt|yay) "$pm" -S $packages $switches --needed && if [ -z "$depinstall" ]; then success; else depsuccess="true"; break; fi;;
-				apk) sudo "$pm" add $packages $switches && if [ -z "$depinstall" ]; then success; else depsuccess="true"; break; fi;;
+				apt|apt-get|yum|dnf|eopkg|zypper) sudo "$pm" install $packages $switches && if [[ -z "$depinstall" ]]; then success; else depsuccess="true"; break; fi;;
+				pkg) "$pm" install $packages $switches && if [[ -z "$depinstall" ]]; then success; else depsuccess="true"; break; fi;;
+				pacman) sudo "$pm" -S $packages $switches --needed && if [[ -z "$depinstall" ]]; then success; else depsuccess="true"; break; fi;;
+				yaourt|yay) "$pm" -S $packages $switches --needed && if [[ -z "$depinstall" ]]; then success; else depsuccess="true"; break; fi;;
+				apk) sudo "$pm" add $packages $switches && if [[ -z "$depinstall" ]]; then success; else depsuccess="true"; break; fi;;
 			esac
 			echo -e "$warnPrefix $pm failed."
 		done
 	fi
-	if ! [ "$depsuccess" = "true" ]; then
+	if ! [[ "$depsuccess" == "true" ]]; then
 		echo -e "$infoPrefix Searching on shoppe repos..."
 		currentpack=0
 		success=0
@@ -138,34 +138,35 @@ pinstall() {
 			if grep "^$package " "$packagefile" &>/dev/null; then
 				yesnotxt="$package is already installed! Install anyways? [y/N] "
 				yesno n
-				if [ "$choice" = "no" ]; then continue; else alreadyinstalled="true"; fi
+				if [[ "$choice" == "no" ]]; then continue; else alreadyinstalled="true"; fi
 			fi
 			success="false"
 			clashes="false"
 			rm -rf "$tmpdir"
 			mkdir "$tmpdir"
-			! [ "$1" = "up" ] && echo -e "$infoPrefix Installing $package..."
+			! [[ "$1" == "up" ]] && echo -e "$infoPrefix Installing $package..."
 			let currentpack++
-			if ! [ "$1" = "up" ]; then echo -e "$infoPrefix Fetching package..."; fetch; fi
-			if ! [ "$success" = "true" ]; then echo -e "$errorPrefix Could not fetch package: $package"; continue; fi
+			if ! [[ "$1" == "up" ]]; then echo -e "$infoPrefix Fetching package..."; fetch; fi
+			if ! [[ "$success" == "true" ]]; then echo -e "$errorPrefix Could not fetch package: $package"; continue; fi
 			cd "$tmpdir"
 			source shoppepkg
-			if [ "$conflicts" ]; then
+			if [[ "$conflicts" ]]; then
 				for clash in $conflicts; do
 					grep "^$clash " "$packagefile" &>/dev/null && clashes="true" && echo -e "$errorPrefix $name clashes with $clash. Remove clashing packages to be able to install $name."
 				done
 			fi
-			if [ "$clashes" = "false" ]; then
-				if ! [ -s "content.tar.gz" ]; then echo -e "$warnPrefix No prebuilt files found, defaulting to build mode..." && nobuild="false"; fi
-				if [ "$makedepends" ]; then depinstall="true"; packages="$makedepends"; pinstall; depsuccess="false"; fi
-				if [ "$depends" ]; then depinstall="true"; packages="$depends"; pinstall; depsuccess="false"; fi
-				if ! [ "$nobuild" = "true" ] && type -t shoppebuild &>/dev/null; then
+			if [[ "$clashes" == "false" ]]; then
+				if ! [[ -s "content.tar.gz" ]]; then echo -e "$warnPrefix No prebuilt files found, defaulting to build mode..." && nobuild="false"; fi
+				if [[ "$makedepends" ]]; then depinstall="true"; packages="$makedepends"; pinstall; depsuccess="false"; fi
+				if [[ "$depends" ]]; then depinstall="true"; packages="$depends"; pinstall; depsuccess="false"; fi
+				if ! [[ "$nobuild" == "true" ]]; then
 					echo -e "$infoPrefix Buidling..."
-					shoppebuild
+					type -t shoppebuild &>/dev/null && shoppebuild
+					echo -e "$infoPrefix Installing..."
+					type -t shoppeinstall &>/dev/null && shoppeinstall
 				fi
-				echo -e "$infoPrefix Installing..."
-				type -t shoppeinstall &>/dev/null && shoppeinstall
-				[ "$nobuild" = "true" ] && tar -xzf content.tar.gz -C content
+				[[ "$nobuild" == "true" ]] && tar -xzf content.tar.gz -C content
+				type -t shoppepostinstall &>/dev/null && shoppepostinstall
 				sudo cp -rf "$tmpdir/content"/* /
 				cd "$tmpdir/content"
 				shopt -s globstar
@@ -175,11 +176,11 @@ pinstall() {
 				shopt -u globstar
 				# NOTE: Bash <4 friendly method:
 				# find ./ -type f | cut -c2- > $packinfodir/$name
-				if [ "$currentsuccess" = "1" ] && ! [ "$alreadyinstalled" = "true" ]; then
+				if [[ "$currentsuccess" == "1" ]] && ! [[ "$alreadyinstalled" = "true" ]]; then
 					# shellcheck disable=SC2154
 					echo "$name $revision" >> $packagefile
 				fi
-				if ! [ "$1" = "up" ]; then
+				if ! [[ "$1" == "up" ]]; then
 					nopt=0
 					for opt in $optional; do
 						let nopt++
@@ -188,18 +189,18 @@ pinstall() {
 				fi
 			fi
 		done
-		if ! [ "$success" = "$currentpack" ]; then
+		if ! [[ "$success" == "$currentpack" ]]; then
 			echo -e "$errorPrefix Failed to install some packages. Double check your spelling."
 			exit 1
 		else
-			! [ "$1" = "up" ] && echo -e "$infoPrefix Installed succesfully." && exit 0
+			! [[ "$1" == "up" ]] && echo -e "$infoPrefix Installed succesfully." && exit 0
 		fi
 	fi
 }
 
 premove() {
-	if [ -z "$packages" ]; then echo -e "$errorPrefix Nothing to remove!"; exit 2; fi
-	if ! [ "$skipfrontend" = "true" ]; then
+	if [[ -z "$packages" ]]; then echo -e "$errorPrefix Nothing to remove!"; exit 2; fi
+	if ! [[ "$skipfrontend" == "true" ]]; then
 		for pm in $installed; do
 			echo -e "$infoPrefix Using $pm..."
 			case $pm in
