most of the frontend (and some install and remove command fixes)

diff --git a/shoppe b/shoppe
--- a/shoppe
+++ b/shoppe
@@ -1,4 +1,4 @@
-#!/usr/bin/bash
+#!/usr/bin/bash -x
 ##
 ## shoppe - a lightweight portable package manager that integrates with your current package manager
 ##
@@ -20,6 +20,9 @@
 # Better documentation on getting started
 # Fix package installation order (dependencies first, full packages last)
 # Clear functions after each install
+
+## TOFIX
+# forcebuild causes dependencies to be assigned to toinstall instead of tofrontend
 
 ### BEGIN CODE ###
 
@@ -46,11 +49,14 @@ pkglist="$configdir/pkglist"
 pkginfo="$configdir/pkginfo"
 tmpdir="$configdir/tmp"
 
+force="false"
+
 [[ ! -e "$configdir" ]] && mkdir "$configdir"
 [[ ! -e "$pkginfo" ]] && mkdir "$pkginfo"
 [[ -e "$configdir/config" ]] && source "$configdir/config"
 [[ ! -e "$configdir/repodata" ]] && mkdir "$configdir/repodata"
 [[ ! -e "$repofile" ]] && echo "http: https://raw.githubusercontent.com/shoppepm/shoppe-repos/master" > "$repofile"
+[[ ! -e "$pkglist.frontend" ]] && touch $pkglist.frontend
 
 ## Helper functions
 yesno() {
@@ -68,6 +74,8 @@ yesno() {
 }
 
 get_source() {
+	# This is a function used to get the source from the source variable.
+	# See docs/shoppepkg.md
     if [[ "$sourcetype" == "compressed" ]]; then
         case $source in
             *.tar.gz) sourcetype="targz";;
@@ -87,6 +95,52 @@ get_source() {
     esac
 }
 
+## Frontend
+
+# Supported package managers:
+availablePM="apt apt-get dnf yum yay yaourt pacaur pacman"
+
+frontend_init() {
+	# This function initializes the frontend.
+	# Usage: frontend_init
+	# See docs/frontend.md
+	[[ "$skipfrontend" == "true" ]] && return 0
+	for pm in $availablePM; do
+		command -v "$pm" &>/dev/null && break
+	done
+	case $pm in
+		apt|apt-get|dnf|yum)
+			frontend_install="sudo $pm install"
+			frontend_remove="sudo $pm remove"
+			frontend_update="sudo $pm update"
+			frontend_upgrade="sudo $pm upgrade"
+			frontend_query="sudo $pm info"
+			;;
+		yay|yaourt|pacaur)
+			frontend_install="$pm -Sy --needed"
+			frontend_remove="$pm -R"
+			frontend_update="$pm -Sy"
+			frontend_upgrade="$pm -Syu"
+			frontend_query="$pm -Q"
+			frontend_listall="$pm -Q"
+			;;
+		pacman)
+			frontend_install="sudo $pm -Sy --needed"
+			frontend_remove="sudo $pm -R"
+			frontend_update="sudo $pm -Sy"
+			frontend_upgrade="sudo $pm -Syu"
+			frontend_query="sudo $pm info"
+			frontend_listall="$pm -Q"
+			;;
+	esac
+}
+
+frontend_harvest() {
+	# This function harvests data from the available frontend.
+	# Usage: frontend_harvest
+	[[ -z "$pm" ]] && return 0
+	$frontend_listall >> $pkglist.frontend
+}
 
 ## Main functions
 
@@ -96,14 +150,21 @@ shoppe_install() {
 	echo -e "$p_info Searching on shoppe repositories..."
 	rm -rf "$tmpdir"
 	mkdir "$tmpdir"
+	[[ -z "$packages" ]] && echo -e "$p_error Nothing to install!" && exit 1
 	[[ ! -e "$configdir/repodata/1" ]] && echo -e "$p_warn No repositories fetched. Running update..." && shoppe_update
 #	totalrepos="$(find $configdir/repodata -mindepth 1 -type f | wc -l)" # total amount of repositories
 	tocheck="$packages"
-	until [[ -z "$tocheck" ]] || [[ "$tocheck" = " " ]]; do
+	# Until there's nothing to scan, get each package to scan and:
+	# - see if the package is actually available in any repository
+	# - fetch the package
+	# - source it and add dependencies to the list of packages to be checked
+	# - check if the package is already installed
+	until [[ -z "${tocheck// }" ]]; do
 		for package in $tocheck; do
 			success="0"
 			idtocheck="1"
-			echo -e "$infoPrefix Fetching package: $package"
+			[[ "$pm" ]] && $frontend_query $package &>/dev/null && tofrontend="$tofrontend $package" && tocheck="${tocheck/$package/}" && continue
+			echo -e "$p_info Fetching package: $package"
 			until [[ ! -e "$configdir/repodata/$idtocheck" ]]; do
 				grep "$package" "$configdir/repodata/$idtocheck" &>/dev/null && success="1" && repo="$idtocheck" && break
 				let idtocheck++
@@ -115,10 +176,18 @@ shoppe_install() {
 				"local: "*) cp "${repotofetch/local\:\ /}/$package/shoppepkg" "$tmpdir/$package/" && success="1"
 							[[ -e "${repotofetch/local\:\ /}/$package/content.tar.gz" ]] && cp "${repotofetch/local\:\ /}/$package/content.tar.gz" "$tmpdir/$package/";;
 				"http: "*)  wget -q "${repotofetch/http\:\ /}/$package/shoppepkg" -O "$configdir/repodata/shoppepkg"
-							! wget -q "${repotofetch/http\:\ /}/$package/content.tar.gz" -O "$configdir/$package/content.tar.gz" && echo -e "$p_warn Prebuilt files not found, defaulting to build mode..." && echo "nobuild='false'" >> "$configdir/$package/shoppepkg";;
+							! wget -q "${repotofetch/http\:\ /}/$package/content.tar.gz" -O "$configdir/$package/content.tar.gz" && echo -e "$p_warn Prebuilt files not found, defaulting to build mode..." && echo "nobuild='false'" >> "$tmpdir/$package/shoppepkg";;
 				*) echo -e "$p_debug Repo data file for id $repo does not contain repository path! Have you been tampering with the file? Run shoppe update to fix this.";;
 			esac
 			source "$tmpdir/$package/shoppepkg"
+			if [[ "$force" != "true" ]] && grep "^$package $revision $pkgver" "$pkglist" &>/dev/null && grep "^$package $revision $pkgver" "$pkglist.frontend" &>/dev/null; then
+				echo "$p_info Package $package is already installed, skipping..."
+				tocheck="${tocheck/$package/}"
+				continue
+				#echo -e "$p_info Package $package is already installed! Install anyways? [y/N]"
+				#yesno n
+				#[[ "$choice" == "no" ]]  && continue
+			fi
 			toinstall="$toinstall $package"
 			[[ ! -z "$depends" ]] && tocheck="$tocheck $depends"
 			[[ "$nobuild" = "false" ]] && [[ ! -z "$makedepends" ]] && toinstall="$tocheck $makedepends"
@@ -126,18 +195,23 @@ shoppe_install() {
 		done
 	done
 	toinstall="$(echo -e "${toinstall}" | sed -e 's/^[[:space:]]*//')"
-	echo -e "$p_info This will install the following packages: "
+	tofrontend="$(echo -e "${tofrontend}" | sed -e 's/^[[:space:]]*//')"
+	[[ -z "$toinstall" ]] && [[ -z "$tofrontend" ]] && echo -e "$p_error Nothing to install!" && exit 1
+	echo -e "  $p_info This will install the following packages: "
 	echo -e "$toinstall"
+	[[ "$tofrontend" ]] && echo -e "  $p_info Using frontend for:\n$tofrontend"
 	echo -e "Continue? [Y/n]"
 	yesno y
 	[[ "$choice" == "no" ]] && exit 1
+	[[ "$tofrontend" ]] && echo -e "$p_info Installing packages from frontend..." && if $frontend_install $tofrontend; then echo -e "$p_info Updating installed package list..." && frontend_harvest; else echo -e "$p_error Failed to install." && exit 1; fi
 	for package in $toinstall; do
 		echo -e "$p_info Installing $package..."
 		let currentpkg++
 		nobuild="true"
-		[[ "$forcebuild" == "true" ]] && nobuild="false"
 		cd "$tmpdir/$package"
 		source shoppepkg
+		[[ "$forcebuild" == "true" ]] && nobuild="false"
+		[[ "$package" != "$pkgname" ]] && echo -e "$p_debug Package name and pkgname do not match (expected $package, got $pkgname). Please contact the package's maintainer."
 		type -t shoppepreinstall &>/dev/null && echo -e "  - $p_info Running pre-install..." && shoppepreinstall
 		if [[ "$nobuild" == "false" ]]; then
 			type -t shoppebuild &>/dev/null && echo -e "  - $p_info Building..." && ! shoppebuild && echo -e "$p_error Failed to build $package." && exit 1
@@ -145,11 +219,13 @@ shoppe_install() {
 		else
 			[[ "$nobuild" == "true" ]] && [[ "$(sha512sum content.tar.gz)" == "$sha512sum" ]] && tar -xzf content.tar.gz
 		fi
-		cd content && ! sudo cp -rf * / && echo -e "$p_error Failed to install $package." && exit 1
+		! sudo cp -rf content/* / && echo -e "$p_error Failed to install $package." && exit 1
+		[[ -e "$pkginfo/$package" ]] && rm -rf "$pkginfo/$package"
 		mkdir "$pkginfo/$package"
 		shopt -s globstar
+		[[ -e "$pkginfo/$package/content" ]] && rm "$pkginfo/$package/content"
 		for file in "$tmpdir/$package/content"/**; do
-			[[ ! -d "$file" ]] && echo "${file/$PWD/}" >> "$pkginfo/$package/content"
+			echo "${file/$PWD/}" >> "$pkginfo/$package/content"
 		done
 		shopt -u globstar
 		type -t shoppepostinstall &>/dev/null && echo -e "  - $p_info Running post-install..." && ! shoppepostinstall && echo -e "$p_warning Post-install script failed, but package's files were already copied! It is reccomended to reinstall the package, and if that doesn't help, contact the package's maintainer."
@@ -158,6 +234,7 @@ shoppe_install() {
 			mv "${pkglist}-tmp" "$pkglist"
 		fi
 		echo "$package $revision $pkgver" >> "$pkglist"
+		if [[ "$nobuild" == "false" ]] && [[ "$makedepends" ]]; then [[ "$depends" ]] && echo "$makedepends $depends" > "$pkginfo/$package/dependencies"; else [[ "$depends" ]] && echo "$depends" > "$pkginfo/$package/dependencies"; fi
 		if [[ "$packagemake" == "true" ]]; then
 			tar -czf content.tar.gz content
 			echo -e "$p_debug sha512sum=$(sha512sum content.tar.gz)"
@@ -167,8 +244,39 @@ shoppe_install() {
 	done
 }
 
+# Remove packages.
+shoppe_remove() {
+	[[ -z "$packages" ]] && echo -e "$p_error Nothing to remove!" && exit 1
+	tocheck="$packages"
+	until [[ -z "${tocheck// }" ]]; do
+		for package in $tocheck; do
+			! grep "^$package " "$pkglist" &>/dev/null && echo -e "$p_info Package $package is not installed, skipping..." && tocheck="${tocheck/$package/}" && continue
+			tocheck="${tocheck/$package/}"
+			tocheck="$tocheck $(cat $pkginfo/$package/dependencies)"
+			toremove="$package"
+		done
+	done
+	[[ -z "$toremove" ]] && echo -e "$p_error Nothing to remove!" && exit 1
+	echo -e "$p_info The following packages will be removed"
+	echo "$toremove"
+	echo -e "Continue? [Y/n]"
+	yesno y
+	[[ "$choice" == "no" ]] && exit 1
+	for package in $toremove; do
+		echo -e "$p_info Removing $package..."
+		! xargs sudo rm -f < "$pkginfo/$package/content" && echo -e "$p_error Failed to remove $package." && exit 1
+		rm -rf "$pkginfo/$package"
+		grep -vwE "^$package " "$pkglist" > "${pkglist}-tmp"
+		mv "${pkglist}-tmp" "$pkglist"
+	done
+}
+
 # Update repository info.
 shoppe_update() {
+	if [[ "$pm" ]]; then
+		echo -e "$p_info Fetching installed package list from frontend..."
+		frontend_harvest
+	fi
 	rm -rf "$configdir/repodata"
 	mkdir "$configdir/repodata"
 	while IFS="" read -r line || [[ -n "$line" ]]; do
@@ -216,10 +324,11 @@ for switch in $shoppeswitches; do
 		"+rawquery"|"+rq") rawquery="true";;
 		"+forcebuild"|"+fb") nobuild="false"; forcebuild="true";;
 		"+packagemake"|"+pm") packagemake="true"; nobuild="false";;
+		"+f"|"+force") force="true";;
 	esac
 done
 [[ "$switch" == *"--noconfirm"* ]] && noconfirm="true"
 
-echo "$command $packages $switches"
+[[ "$skip_frontend" != "true" ]] && frontend_init
 
 $command
