FIX: Fix content tarballs containing content directory instead of standard content directories

diff --git a/shoppe b/shoppe
--- a/shoppe
+++ b/shoppe
@@ -165,7 +165,7 @@ get_source() {
         git) git clone "$source" "source";;
         git-tag) git clone --branch "$tag" "$source" "source";;
         tar) wget "$source"; tar xvf ./* -C source;;
-        targz) wget "$source"; tar xzf ./* -C source;;
+        targz) wget "$source"; mkdir source; tar xzf ./* -C source;;
         #gz) wget "$source"; gunzip ./*;;
         tarxz) wget "$source"; tar xJf ./* -C source;;
 		zip) wget "$source"; mkdir source; unzip ./* -d source;;
@@ -270,8 +270,30 @@ pkg_install() {
 		cd "$tmpdir/$package"
 	else
 		contentchecksumvar="content_${arch}_checksum"
+		mkdir "$tmpdir/$package/content"
 		# shellcheck disable=SC2154
-		[[ "$nobuild" == "true" ]] && [[ "$(sha512sum content-$arch.tar.gz)" == "${!contentchecksumvar}" ]] && tar -xzf content-$arch.tar.gz -C content && echo -e "$p_info Successfully extracted package."
+		if [[ "$nobuild" == "true" ]] && [[ "$(sha512sum content-$arch.tar.gz)" == "${!contentchecksumvar}" ]]; then
+			if tar -xzf content-$arch.tar.gz -C content; then
+				echo -e "$p_info Successfully extracted package."
+			else
+				echo -e "$p_error Failed to extract $package."
+				exit 1
+			fi
+		else
+			echo -e "$p_warn Package checksum (${!contentchecksumvar}) does not match the content tarball's checksum ($(sha512sum content-$arch.tar.gz))."
+			yesnotxt="Install anyways (not reccomended)?" yesno n
+			if [[ "$choice" == "yes" ]]; then
+				if tar -xzf content-$arch.tar.gz -C content; then
+					echo -e "$p_info Successfully extracted package."
+				else
+					echo -e "$p_error Failed to extract $package."
+					exit 1
+				fi
+			else
+				echo -e "$p_error Failed to install $package."
+				exit 1
+			fi
+		fi
 	fi
 	! cd content && echo -e "$p_error Failed to install $package." && exit 1
 	! $suauth cp -rf . / && echo -e "$p_error Failed to install $package." && exit 1
@@ -496,7 +518,8 @@ shoppe_install() {
 		let currentpkg++
 		pkg_install
 		if [[ "$packagemake" == "true" ]]; then
-			tar -czf content-$arch.tar.gz content
+			cd "$tmpdir/$package/content"
+			tar -czf content-$arch.tar.gz .
 			echo "content_${arch}_checksum=$(sha512sum content-$arch.tar.gz)" >> "$tmpdir/$package/shoppepkg"
 			mkdir "$tmpdir/$package/topackage"
 			mv content-$arch.tar.gz "$tmpdir/$package/topackage"
